### ISSUE TITLE
deal with nan in coadd

### ISSUE THREAD

**Issue by esheldon** [LSSTDESC/descwl_coadd#12]
there can be cases where there are no exposures over part of the coadd

make sure that no nan or other sentinels are being sent to metacal

**Comment by esheldon** [comment]
may want to deal with this in metadetect

**Comment by beckermr** [comment]
This shouldn't happen for our sims. Can you plot some images for one or point me to a case where this happened?

**Comment by esheldon** [comment]
what I saw was nan in the variance of the coadd, but I think this implies nan in the coadd or some other sentinel

**Comment by esheldon** [comment]
with the rotations it is plausible there is no information in some part of the final coadd

**Comment by beckermr** [comment]
Ahhhhh I forgot. So I make the SE observations sqrt(2) bigger than the coadd. This doesn't account for shear, but for realistic shear levels in the WCS, the central 300 pixels should always be covered. I think we should cut down to those. This is how I do my own sims.

**Comment by esheldon** [comment]
I think we should leave in the possibility of such gaps because in real data they will exist.

I think the coadd code does something sensible with this, so probably it is downstream when we send the images to metacal that we need to be careful.

**Comment by esheldon** [comment]
I checked, the image also gets nan

**Comment by beckermr** [comment]
Do they set mask bits?

**Comment by esheldon** [comment]
probably, I've not dealt at all with mask stuff yet

**Comment by esheldon** [comment]
in #3 I am currently setting the image and noise image to zero where the variance is zero (turning nan to 0)

Might want to replace with noise
