### ISSUE TITLE
Count fraction of input images masked at each pixel rather than rely on ormask

### ISSUE THREAD

**Issue by esheldon** [LSSTDESC/descwl_coadd#48]
This may explain why cutting on masked fraction wasn't helping as much as we expected

**Comment by esheldon** [comment]
Also  need to rethink if we should be counting CR, SAT, BAD here, as it is in the ormask.  For a deep stack that should not matter.

Following DES work should be checking the fraction of times the pixel is masked in the stack; will be small when nepoch = 100 for CR, SAT, BAD but not for BRIGHT

**Comment by beckermr** [comment]
💯 

We also need to code up the masked fraction measurements in a fixed aperture so that we can make the cuts later.

**Comment by esheldon** [comment]
Actually, BRIGHT is being counted.

I forgot I converted BRIGHT to INTERP because the stack doesn't currently know about BRIGHT (but we will start adding that plane in the sims)

**Comment by esheldon** [comment]
sorry SAT not INTERP

**Comment by esheldon** [comment]
So the real issue is
* in the short term just count SAT (also == BRIGHT) but not others
* need to add the BRIGHT plane
* turn off counting CR and maybe BAD
* keep masked fraction as said above and downstream do gauss weighted aperture of that

**Comment by beckermr** [comment]
I am confused. We need to count any pixel where an interpolation has been applied. That could include BAD, CR, SAT, or BRIGHT, right?

**Comment by esheldon** [comment]
right, but currently it is based on the ormask rather than fraction of images that had the value set.  The current setup only makes sense when nepochs ~ 1

**Comment by esheldon** [comment]
(note I'm currently running with 1 epoch per band so it is fine, but for real data or large nepoch in sims we need to do better)

**Comment by esheldon** [comment]
However, with rotations we may not even care about CR, BAD since they will never land on the same part of the coadd.

Maybe all we will care about is BRIGHT (currently remapped to SAT) in which case the ormask would be fine

**Comment by beckermr** [comment]
I totally get that we will not care with tons of epochs, but we should count everything consistently and then make one cut.

**Comment by esheldon** [comment]
There is a tool for this in DM land, called a mask propogation threshold, which only sets the mask bit if a certain fraction of input exposures are set at a given location.

Still not quite what we want, but can be a stopgap

**Comment by beckermr** [comment]
Yup. Unfortunately, it makes us have to choose the threshold when making the coadd. This is fine for sims but won't be useful when looking at data.

**Comment by esheldon** [comment]
agreed

**Comment by esheldon** [comment]
for the online coadding code
```
- set `bit_mask_value` to only EDGE or some minimal set since these pixels do not get coadded.  Actually would be better to discount the EDGE pixels when doing the intersection of CCD image and coadd region
- set `mask_threshold_dict` to include everything we want in the mfrac
- use `rejected_weights_by_bit` to create mfrac
```

**Comment by esheldon** [comment]
We might just set `mask_threshold_dict = {}` and do this ourselves so we have control over it
