### ISSUE TITLE
In CoaddObs ensure modifications to image/weight/mask etc. are reflected in the .coadd_exp etc.

### ISSUE THREAD

**Issue by esheldon** [LSSTDESC/descwl_coadd#72]
This CoaddObs was adopted so it could be sent directly to the metacal code.

But it is keeping exps around so it can propagate the sheared images into deep copies of the exps for input to the lsst algorithms.

Make sure we have data consistency.

**Comment by esheldon** [comment]
This is a mess.  It might be worth it to make .exposure fully supported in Observation and make sure that it syncs the image data and mask data (with bmask not ormask)

**Comment by beckermr** [comment]
I'd stick to only dm data structures here. Then in the dm task we use to run metacal, do the conversion to an ngmix obs there.

**Comment by esheldon** [comment]
On Tue, Nov 9, 2021 at 9:29 AM Matthew R. Becker ***@***.***>
wrote:

> I'd stick to only dm data structures here. Then in the dm task we use to
> run metacal, do the conversion to an ngmix obs there.
>

I need to process sims as well, so this needs to live outside of the task.

**Comment by beckermr** [comment]
I'd argue that we are not very concerned about bugs in copying attributes and so more than one copy of this can live in various places.
