### ISSUE TITLE
make separate stack exposures for all band caodd and per band coadds

### ISSUE THREAD

**Issue by esheldon** [LSSTDESC/descwl_coadd#9]

**Comment by esheldon** [comment]
the coadd code is modifying them internally, causing problems

**Comment by beckermr** [comment]
So my plan on this was to actually have a method attached to the SimSEObs that would convert it to a stack-based object. Should we do that instead? This could should really stick to stack APIs everywhere.

**Comment by esheldon** [comment]
that could be useful, but note that we eventually need to convert to an Observation like thing for the metadetect code

**Comment by esheldon** [comment]
(so the coadd code itself will still produce an Observation like thing)

**Comment by beckermr** [comment]
Right. I am talking about my random `SEObs` thing to `stack`.

**Comment by esheldon** [comment]
turns out this was a red herring; when there are only two exposures in a coadd the stack seems to set the variance to nan
